name = "shadow-cloak"
account_id = "b2471e0c307123945bdf1ce1b025563f"
main = "shadow-cloak.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "godview-clicks"
database_id = "3f7ed41d-1ec6-4519-8b0d-eda22ae9b00c"

[[kv_namespaces]]
binding = "CLOAKER_CONFIG"
id = "cfca8f5e3aa84d33b889cddfc5d5763c"

[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "cloak-assets"
