name = "cloak-admin-api"
account_id = "61f1eb800e48d2cf41ed9ddacf01581b"
main = "cloak-admin-api.js"
compatibility_date = "2024-12-01"

# ── Production (default) ──────────────────────────────────────────────────────
[[d1_databases]]
binding = "DB"
database_name = "godview-clicks"
database_id = "81360d40-f713-4f02-8d0d-ad8e69e65c09"

[[kv_namespaces]]
binding = "CLOAKER_CONFIG"
id = "d41d974032014541a38214f30df1cb41"

[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "cloak-assets"

# ── Staging ───────────────────────────────────────────────────────────────────
[env.staging]
name = "cloak-admin-api-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "godview-clicks-staging"
database_id = "a94ce480-39e7-48a5-ae90-9c58510be191"

[[env.staging.kv_namespaces]]
binding = "CLOAKER_CONFIG"
id = "5cbffe5c23d44f24a47be57ebf4ea7e1"

[[env.staging.r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "cloak-assets"
