name = "shadow-cloak-staging"
account_id = "61f1eb800e48d2cf41ed9ddacf01581b"
main = "shadow-cloak.js"
compatibility_date = "2026-05-03"

[[d1_databases]]
binding = "DB"
database_name = "godview-clicks-staging"
database_id = "a94ce480-39e7-48a5-ae90-9c58510be191"

[[kv_namespaces]]
binding = "CLOAKER_CONFIG"
id = "5cbffe5c23d44f24a47be57ebf4ea7e1"
