name = "line-redirect"
account_id = "61f1eb800e48d2cf41ed9ddacf01581b"
main = "line-redirect.js"
compatibility_date = "2026-05-03"

[[d1_databases]]
binding = "DB"
database_name = "godview-clicks"
database_id = "81360d40-f713-4f02-8d0d-ad8e69e65c09"
